default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  socket: 5432
  username: smb
  password: smb

development:
  <<: *default
  database: search_mhw_bounty_dev

test:
  <<: *default
  database: search_mhw_bounty_test

production:
  <<: *default
  database: search_mhw_bounty
