default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %>
  socket: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
